# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.14.6
    build: .
    ports:
      - 8080:8080 # site will be available at http://localhost:8080
      - 35729:35729 # livereload port
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --force_polling
